#ifndef RATIOS_H
#define RATIOS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 480

#define CENTER_PANEL_WIDTH SCREEN_WIDTH * 82.5/100
#define CENTER_PANEL_HEIGHT SCREEN_HEIGHT

#define SIDE_PANEL_WIDTH 70
#define SIDE_PANEL_HEIGHT SCREEN_HEIGHT

#define FOCUS_PANEL_WIDTH CENTER_PANEL_WIDTH
#define FOCUS_PANEL_HEIGHT CENTER_PANEL_HEIGHT * 56.25/100

#define TOP_PANEL_WIDTH CENTER_PANEL_WIDTH
#define TOP_PANEL_HEIGHT CENTER_PANEL_HEIGHT * 21.875/100  // (100 - 56.25) / 2

#define BOTTOM_PANEL_WIDTH CENTER_PANEL_WIDTH
#define BOTTOM_PANEL_HEIGHT CENTER_PANEL_HEIGHT * 21.875/100

#define TIMING_PANEL_WIDTH FOCUS_PANEL_WIDTH * 25.0/100
#define TIMING_PANEL_HEIGHT FOCUS_PANEL_HEIGHT

#define DATA_PANEL_WIDTH FOCUS_PANEL_WIDTH * 25.0/100
#define DATA_PANEL_HEIGHT FOCUS_PANEL_HEIGHT

#define SPEEDOMETER_PANEL_WIDTH FOCUS_PANEL_WIDTH * 50.0/100
#define SPEEDOMETER_PANEL_HEIGHT FOCUS_PANEL_HEIGHT


#endif