#ifndef RATIOS_H
#define RATIOS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 480

#define SIDE_BAR_WIDTH 100
#define CENTRAL_PANEL_WIDTH 600
#define BOTTOM_BAR_HEIGHT 80
#define TOP_BAR_HEIGHT 80
#define DATA_PANEL_HEIGHT 320
#define DATA_LEFT_WIDTH 150
#define DATA_RIGHT_WIDTH 150
#define DATA_CENTER_WIDTH 300

#endif