#ifndef STEER_CALIBRATION_H
#define STEER_CALIBRATION_H

#include "lvgl.h"
#include "utils.h"

#define TOP_BAR_HEIGHT 50
#define TOP_BAR_WIDTH SCREEN_WIDTH
#define TOP_LABELS_HEIGHT 50
#define TOP_LABELS_WIDTH SCREEN_WIDTH
#define CALIBRATION_TOOL_HEIGHT 150
#define CALIBRATION_TOOL_WIDTH SCREEN_WIDTH
#define BUTTONS_ROW_HEIGHT 170
#define BUTTONS_ROW_WIDTH SCREEN_WIDTH
#define BOTTOM_LABELS_HEIGHT 30
#define BOTTOM_LABELS_WIDTH SCREEN_WIDTH 

#define BTN_HEIGHT 150
#define BTN_WIDTH 290

#define TOOL_BAR_HEIGTH 65
#define TOOL_BAR_WIDTH 730

void steer_calibration(lv_obj_t *parent);

#endif